Shp 02
gerardolgvr/shipping_app pull request #4
Opened 2020-09-04 05:46 UTC by gerardolgvr

As user, when the package type is selected then the package types are loaded. 
* Percentage is obtained

2020-09-04 18:47 UTC, lramirezEncora requested changes

2020-09-04 22:01 UTC, gerardolgvr commented on src/main/java/dev/gerardo/shippingapp/controller/PackageSizeController.java
> +            uiPackageSizes = sizes.stream().map(PackageSize::getDescription).collect(Collectors.toList());
fixed, thanks

2020-09-05 01:47 UTC, grunger94 commented on src/main/java/dev/gerardo/shippingapp/service/PackageSizeService.java
> +            logger.error("An error ocurred trying to parse package sizes: {}", response);
Doesn't make much sense to log the value of the response if you know beforehand it will be empty

2020-09-05 01:47 UTC, grunger94 commented on src/test/java/dev/gerardo/shippingapp/service/PackageSizeServiceTest.java
> +        String json = "[{\"id\":4,\"description\":\"Small\",\"priceFactor\":10},{\"id\":5,\"description\":\"Medium\",\"priceFactor\":25},{\"id\":6,\"description\":\"Large\",\"priceFactor\":50}]";
Json is duplicate in this class, please make it a variable. You can also build the POJO and transform it into a string using ObjectMapper

2020-09-11 01:34 UTC, jass-holguin approved these changes

2020-09-11 01:34 UTC, merged